export const testData = {
  Url: "https://www.lambdatest.com/selenium-playground/",
  WelcomeMessage: "Welcome to LambdaTest",
  userName: "Vasantha kumar Boddu",
  Email: "vasanthakaju5258@gmail.com",
  Password: "Test@123",
  Company: "Lambda",
  Website: "www.lambda.com",
  Country: "United States",
  City: "Texas",
  Address1: "Street line1",
  Address2: "Street line2",
  State: "Texas",
  Zip: "76330",
  SucessMessage: "Thanks for contacting us, we will get back to you shortly.",
};
