name: Playwright with Hyperexecute
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
        
jobs:
  PW-HyperExecute:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download HyperExecute CLI
        run: |
          curl -O https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
          chmod +x hyperexecute
          sudo mv hyperexecute /usr/local/bin
      
      - name: Run Playwright Tests on HyperExecute
        shell: bash
        run: |
          ./hyperexecute --user ${{ github.event.inputs.username }} --key ${{ github.event.inputs.accessKey }}  --config .autosplit.yaml
          echo "Test completion"
